### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by mivdnber** [Hardtack/Flask-aiohttp#2]
Being able to do `pip install flask-aiohttp` would be nice.

**Comment by hardtack** [comment]
I'm agonizing over whether to upload it to PyPI or not. Because it is a **experimental** project for checking compatibility of WSGI with asyncio. (And it's not compatible enough.)

There are many problems occur from WSGI middleware and I can't fix it since WSGI does not support asynchronous.

It can be useful if you really want to use Flask on asyncio. But if your goal is just using asynchoronous networking, using Tornado, Twisted or aiohttp will be much better solution.

Should I upload a package that has problem cannot be resolved?

**Comment by mivdnber** [comment]
In hindsight, I don't think you should just yet. You can already install it with
`pip install git+https://github.com/Hardtack/Flask-aiohttp.git`
anyway. If you want the git repo to show up in `pip freeze`, do
`pip install -e git+https://github.com/Hardtack/Flask-aiohttp.git#egg=Flask-aiohttp`

**Comment by ninjatrench** [comment]
I would suggest one thing, create a separate flask extension of this and put it in pypi as it is very useful to use with flask and works pretty fine, because projects on pypi are very easy to integrate with.
